### PR TITLE
fix: ignore redis error on rate limit

### LINKED ISSUE #289: fix: silently fail on rate-limit unavailability
rate-limit should ignore all errors on redis failure, and let everything go through

### PR DESCRIPTION
**Pull request by wa0x6e**
## 🧿 Current issues / What's wrong ?

On redis connection issues, rate-limit middleware is blocking the whole request workflow, and not letting through any requests.

## 💊 Fixes / Solution

Fix #289 

On redis connection issues, rate-limit middleware should be ignored, and all requests should bypass the middleware.

## 🚧 Changes

- Bypass rate-limit middleware when redis is not ready
- Update `rate-limit-redis` package to 3.1.0, to support redis reconnection, else will throw https://github.com/express-rate-limit/rate-limit-redis/issues/144

## 🛠️ Tests

- Start your redis server
- yarn dev
- Send some requests to localhost:3001
- It should returns headers like `Ratelimit-Limit`
- Stop the redis server
- It should start logging connections error on the `yarn dev` console
- Send some requests to localhost:3001
- It should return results as usual
- The headers `Ratelimit-Limit` should be missing from the headers
- Start redis again
- Send some requests to localhost:3001
- Headers `Ratelimit-Limit` should be back

### CODE REVIEW

File: src/helpers/rateLimit.ts [hunk 1]
```diff
@@ -18,6 +18,7 @@ export default rateLimit({
       429
     );
   },
+  skip: () => redisClient && !redisClient.isReady,
```
Comment (ChaituVR) [inline src/helpers/rateLimit.ts:21]:
```suggestion
  skip: () => !redisClient?.isReady,
```

**Review by ChaituVR — APPROVED** [review]
tAck
