### PR TITLE
fix: enforce proposal `end` date to be in the future

### LINKED ISSUE #214: Allow proposals only when `end` param is greater than current timestamp
Related to https://github.com/snapshot-labs/snapshot/issues/3339

### PR DESCRIPTION
**Pull request by wa0x6e**
Fix #214 

Enforce proposal `end` property to be in the future

### CODE REVIEW

**Review by ChaituVR — APPROVED** [review]
utAck

File: src/writer/proposal.ts [hunk 1]
```diff
@@ -46,6 +46,11 @@ export async function verify(body): Promise<any> {
     return Promise.reject('wrong proposal format');
   }
 
+  const tsInt = (Date.now() / 1e3).toFixed();
+  if (msg.payload.end < tsInt) {
```
Comment (ChaituVR) [inline src/writer/proposal.ts:50]: I feel like we can make it "Not to be in past"
```suggestion
  if (msg.payload.end <= tsInt) {
```
